url:              http://rapkin.com.ua
author:           Mikola Parfenyuck
email:            mikola.parfenyuck@gmail.com
title:            rapkin | Software developer
description:      Little blog about my little projects.

highlighter:      pygments
permalink:        /:categories/:title/
googleAnalytics:  UA-37531241-1
markdown:         redcarpet
redcarpet:
    extensions: ["strikethrough", "tables"]

twitter_username: i_rapkin
github_username:  rapkin
vk_username:      i_rapkin
repo:             https://github.com/rapkin/rapkin.github.io
